import 'package:flutter/material.dart';
import 'package:flutter_app/texte/texte.dart';

class francePopulation extends StatelessWidget {
  const francePopulation({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(10.0),
      child: ListView(
        physics: BouncingScrollPhysics(),
        children: [
          new Container(
            padding: EdgeInsets.all(10),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                TitreH1('  I  ', ' Demographie'),
                DefaultText("D'après l'Institut national de la statistique et des études économiques (INSEE), 66 991 000 personnes vivent en France au 1er janvier 2017 (hors COM et Nouvelle-Calédonie), dont 64 860 000 en métropole et 2 131 000 dans les départements d'outre-mer . Si on inclut également les 604 000 habitants des collectivités d'outre-mer (Polynésie française, SaintPierre-et-Miquelon, Wallis-et-Futuna, Saint-Martin et Saint-Barthélemy) et de Nouvelle-Calédonie, la population de l'ensemble des territoires français atteint environ 67,6 millions d'habitants, soit environ 0,9 % de la population mondiale . Un recensement national général était organisé à intervalles réguliers depuis 1801, mais depuis janvier 2004, le recensement est réalisé tous les ans dans les communes de 10 000 habitants ou plus, hors collectivités d'outre-mer, et tous les cinq ans ailleurs ."),
                DefaultText("Après avoir été relativement faible au e siècle et au début du e siècle — la France a connu une transition démographique rapide et peu marquée —, la croissance démographique de la France est devenue l'une des plus fortes d'Europe, combinant un taux de natalité supérieur à la moyenne européenne (800 000 naissances en 2015 contre 600 000 décès) et un solde migratoire positif (environ 47 000 individus en 2015) : la population de la France s'est accrue de 0,4 % en 2015 ."),
                DefaultText("En 2015, le taux de fécondité en France est d'environ 1,96 enfant par femme . En 2014, 29,2 % des nouveau-nés (hors Mayotte, COM et NouvelleCalédonie) avaient au moins un parent né à l'étranger et 25,7 % au moins un parent né hors de l'Union européenne ."),
                CustomImageCard("assets/220px-French_residency_by_country_of_nationality_1999.PNG", "Pays d'origine de l'immigration en France (2006)."),
                DefaultText("D'après les projections de la population d'Eurostat, la France devrait compter 72,7 millions d'habitants en 2040, 75,6 millions en 2060, et 78,8 millions en 2080 (en excluant les territoires d'outre mer et la Nouvelle Calédonie)."),
                DefaultText("En outre, la structure de la pyramide des âges évolue depuis le début du e siècle. La part de la population la plus âgée augmente, en raison à la fois de la progression de l'espérance de vie (la France jouit d'une des plus grandes espérances de vie au monde ) et de l'arrivée au troisième âge de la génération du baby boom — phénomène communément appelé le papy boom. La proportion des plus de 60 ans dans la population française est ainsi passée de 17 % à 25 % entre 1980 et 2016, et devrait approcher le tiers en 2050 selon l'Insee ."),
                
              ],
            ),
          ),
          new Container(
            margin: EdgeInsets.only(top: 50),
            padding: EdgeInsets.all(10),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                TitreH1('  II  ', ' Immigration, population étrangère et minorités visibles'),
                DefaultText("En 2015, selon l'historien Pascal Blanchard, entre 12 et 14 millions de Français (soit 18 % à 22 % de la population totale) ont au moins un de leurs grands-parents né dans un territoire non européen ."),
                DefaultText("En 2010, la France accueille, selon la définition internationale des Nations unies (« personne née dans un autre pays que celui où elle réside »), 7,2 millions d'immigrés, soit 11,1 % de la population, dont 5,1 millions (7,8 %) nés hors de l'Union européenne. Elle se classe au sixième rang mondial, derrière les États-Unis (42,8 millions), la Russie (12,3), l'Allemagne (9,8), l'Arabie saoudite (7,3), le Canada (7,2) mais elle devance en revanche le Royaume-Uni (7,0), l'Espagne (6,4) et l'Italie (4,8) . La France est également l'un des pays de l'Union européenne qui compte proportionnellement le plus de personnes issues de l'immigration (1re et 2e générations) parmi les personnes âgées de 25 à 54 ans avec 13,1 % d'immigrés et 13,5 % d'enfants d'au moins un immigré, soit un total de 26,6 %, devant notamment le Royaume-Uni (24,4 %), les Pays-Bas (23,5 %), la Belgique (22,9 %), l'Allemagne (21,9 %) et l'Espagne (20,2 %) . Selon la définition française (INSEE), plus restrictive (nés étrangers hors du territoire), la France comptait en 2015, 6,170 millions d'immigrés, soit 9,3 % de la population."),
                DefaultText("Depuis 1946, le nombre et la part d'immigrés en France augmente de manière continue : 1,986 millions en 1946 (4,98 % de la population totale), 4,037 millions en 1982 (7,43 % de la population totale), 5,342 millions en 2008 (8,44 % de la population totale). Les enfants d'immigrés représentaient 10,4 % de la population totale en 2013. Il y avait donc 12,5 millions d'immigrés et enfants d'immigrés en France en 2013, soit 19,3 % de la population. Les immigrés vivant en France en 2015 étaient originaires à 44,6 % d'Afrique (27 % en 1975), à 35,4 % d'Europe (66 % en 1975), à 14,3 % d'Asie (4 % en 1975) et à 5,6 % d'Amériques ou d'Océanie (2 % en 1975). En 2015, 2,997 millions d'immigrés étaient de sexe masculin et 3,171 millions d'immigrés étaient de sexe féminin. En 2013, 39 % des immigrés en France disposaient de la nationalité française, ce chiffre était de 28 % en 1975 et 16 % en 1911 . La France a un solde migratoire positif. Selon l'INSEE, l'excédent migratoire en 2014 en France était de 32 300 personnes, soit 0,05 % de la population totale ."),
                DefaultText("D'après Michèle Tribalat, il y aurait 3,8 millions personnes d'origine maghrébine en France en 2011 . Il y aurait aussi, selon Jean-Paul Gourévitch, environ 3,5 millions de personnes noires en France en 2008, dont 2,4 millions vivant en France métropolitaine . En 2018, la communauté turque est estimée à 630 000 personnes en France . En 2014, il y avait près de 600 000 Chinois en France, dont 50 000 étaient étudiants . En 2010, on estime à 150 000 le nombre de Vietnamiens en France, ils vivent très majoritairement en région parisienne ."),
                DefaultText("Les immigrés perçoivent des revenus inférieurs d'un tiers en moyenne à ceux des non-immigrés , sont deux fois plus nombreux à ne pas être diplômés et trois fois plus nombreux à vivre sous le seuil de pauvreté . Toutefois, à situation sociale égale, leur formation scolaire et leurs revenus sont proches de ceux des Français nés en France . Selon des travaux, publiés en 2015, de l'économiste Hippolyte d'Albis, les migrants permettent une augmentation du PIB par habitant et une baisse du taux de chômage, en cela ils ont un effet positif sur l'économie ."),
                DefaultText("Les populations d'origine immigrée, et celles qui appartiennent à des minorités visibles, sont parfois victimes de discriminations en France . Pour des raisons indéterminées et sujettes à débats, une partie de cette population se tourne vers le fondamentalisme religieux . Pourtant, on assiste à une certaine convergence des modes de vie des populations immigrées et des Français de longue date . En 2019, le taux de chômage des personnes immigrées est de 16,3 %. Quelque 5,4 millions d'emplois sont interdits aux immigrés non-européens, soit plus d'un emploi sur cinq. Par ailleurs, 26,1 % des familles immigrées vivent dans un logement trop étroit, soit 3,7 fois plus que les personnes non immigrées ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),

                TitreH1(' III ', ' Famille, sexualité et égalité des sexes'),
                DefaultText("Le français est la langue très majoritairement parlée en France et est officiellement « la langue de la République » depuis la loi constitutionnelle de 1992. La France est le deuxième pays francophone le plus peuplé du monde après la République démocratique du Congo , mais le premier en termes de locuteurs. La France mène une politique linguistique active en faveur du français . Celle-ci peut être visible entre autres au sein de l'Organisation internationale de la francophonie dont la France fait partie de même qu'au sein de l'Assemblée parlementaire de la francophonie dont la France fait aussi partie"),
                DefaultText("Depuis la loi du 9 décembre 1905, les Églises sont strictement séparées en droit de l'État en France : « La République ne reconnaît, ne salarie ni ne subventionne aucun culte . » Pour des raisons historiques, l'Alsace-Moselle et la Guyane font exception. La première car elle n'était pas française en 1905 et a conservé son droit local après la réunification ; le culte catholique, deux cultes protestants et le culte israélite y sont reconnus . La deuxième car la loi de 1905 sur la séparation de l'Église et de l'État ne s’applique pas en Guyane qui reste sous le régime de l’ordonnance royale de Charles X du 27 août 1828 . La religion catholique est également toujours reconnue dans certains départements et territoires d'outre-mer. La notion de laïcité et la réglementation qui en découle sont l'objet de débats comme, en 2003-2004, au sujet de la loi sur les signes religieux dans les écoles publiques ."),
                CustomImageCard("assets/300px-Fertility_rate_world_map_2.png", "Taux de fécondité par pays (2020), Population Reference Bureau."),
                DefaultText("La France est un pays laïc avec une grande tradition catholique ancienne, et bien que le poids de l'Église soit en train de diminuer, 48 % des personnes interrogées se déclaraient catholiques lors de sondages publiés en 2019, tandis qu'une part importante de la population se dit agnostique, athée ou sans religion. De plus, d'autres religions sont présentes dans des proportions moins importantes, notamment le judaïsme depuis l'Antiquité, différentes branches du protestantisme depuis la Réforme et l'islam depuis l'arrivée en France d'immigrés du Maghreb et du Moyen-Orient au e siècle. Diverses Églises chrétiennes (néo-apostolique, apostolique arménienne, Mormons, Témoins de Jéhovah, mennonites…) et d'autres religions (hindouisme, bouddhisme, bahaïsme, alévisme…) sont également présentes sur le territoire national, parfois depuis plusieurs siècles (mennonites d'Alsace)."),
                DefaultText("On dénombre en France 42 258 églises et chapelles paroissiales , 2 449 lieux de culte musulmans et 794 synagogues ."),
                DefaultText("Au-delà de ces valeurs, la perte d'influence des religions est un aspect majeur de l'évolution de la société française aux e et e siècles, bien qu'elle s'évalue très différemment d'une région à l'autre. Près de 80 % des hommes et 70 % des femmes qui se disent d'origine catholique n'assistent jamais à un service religieux . Même chez les catholiques les plus fervents, l'obéissance stricte aux préceptes de l'Église diminue : 31 % des pratiquants assidus ayant eu des enfants entre 1995 et 2004 les ont eus hors mariage [source insuffisante]"),
                DefaultText("Les Français ont une image plutôt négative de la religion en général. Selon un sondage Ipsos publié en 2017, 61 % des Français pensent que la religion cause plus de tort que de bien, et seulement 16 % des Français pensent que les personnes croyantes font de meilleurs citoyens ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),

                TitreH1(' IV ', ' Santé et protection sociale'),
                TitreH2(' IV-A ', ' Protection sociale'),
                DefaultText("Depuis sa création en 1945 , la Sécurité sociale est au cœur du système de protection sociale français, bien que l'État, les collectivités territoriales et les mutuelles aient également un rôle important . Le maintien des régimes de protection sociale dont disposaient certaines professions avant 1945 explique la grande complexité du système , qui ne compte pas moins de 120 régimes de base et 1 200 régimes complémentaires . Le régime général de la Sécurité sociale, qui compte de loin le plus grand nombre d'affiliés , est divisé en quatre branches correspondant aux quatre risques majeurs, la maladie, les accidents du travail et maladies professionnelles, les risques liés à la vieillesse et la famille . Si cette protection sociale ne concernait dans un premier temps que les personnes actives, elle s'est peu à peu étendue à toute la population active comme inactive dans beaucoup de domaines, par exemple lors de la création de la couverture maladie universelle (CMU) en 1999 . En outre, à la fin des années 1990, six millions de personnes dépendaient des minima sociaux ."),
                DefaultText("Les prestations sociales sont principalement financées par les cotisations sociales versées par les actifs (65,5 % du total en 2005 ), mais aussi — et de plus en plus — par l'État et les collectivités territoriales . En 2005, les dépenses de protection sociale — au sens le plus large du terme — représentaient près de 30 % du PIB et plus de 45 % du revenu disponible ajusté des ménages . Malgré les efforts menés par les gouvernements successifs pour maîtriser les dépenses sociales , celles-ci augmentent rapidement , du fait notamment de l'augmentation des dépenses de santé des ménages et du vieillissement de la population — le rapport actifs sur inactifs de plus de 60 ans, qui était de 3 en 1970, devrait atteindre 2,07 en 2010 et 1,36 en 2050 en métropole, selon l’Insee ."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' IV-B ', ' Santé'),
                DefaultText("Le système de santé français est en grande partie financé par la branche maladie de la Sécurité sociale. Le nombre de médecins pour 1 000 habitants était de 3,22 en 2008, un des taux les plus élevés au monde . Les Français bénéficient également d'une des espérances de vie les plus longues du monde , même si le taux de mortalité prématurée (avant 65 ans) est élevé . Les dépenses de santé par habitant étaient de 4 719 Dollars par an en 2008 , ce qui place la France au-dessus de ses grands voisins européens, mais en dessous de la Suisse, de la Norvège, du Danemark, du Luxembourg, et des États-Unis. De 1950 à 2006, la dépense consacrée aux soins et aux biens médicaux est passée de 2,5 % à 8,8 % du PIB ."),
                DefaultText("Néanmoins, la santé des habitants de la France n'est pas optimale dans tous les domaines. Malgré la chute de la consommation de vin depuis les années 1960 , les Français demeurent les seconds consommateurs d'alcool d'Europe occidentale, après les Irlandais . 29 % des 18-75 ans fumaient quotidiennement en 2005, malgré les intenses campagnes de lutte contre le tabagisme . Quant aux drogues illicites, la plus consommée est le cannabis : 39 % des hommes de 18 à 25 ans en auraient consommé en 2005, selon l'Observatoire français des drogues et toxicomanies ."),
                CustomImageCard("assets/200px-P1000513_Paris_XIII_Salpetrière_reductwk.JPG", "Le CHU de la Pitié-Salpêtrière, un hôpital d'enseignement à Paris, l'un des plus grands hôpitaux d'Europe ."),
                DefaultText("Contrairement aux idées reçues, la France ne consomme pas significativement plus d'antidépresseurs que les autres pays , le taux de suicide n'y est pas non plus particulièrement plus élevé que dans les autres pays développés . Le taux de troubles de la santé mentale et l'abus de substances, bien qu'élevé, est comparable à celui des autres pays occidentaux ."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),

                TitreH1(' V ', ' Education'),
                DefaultText("En France, l'école publique est laïque et gratuite . Si la formation et la rémunération des enseignants, ainsi que le choix des programmes, sont du ressort de l'État, la gestion des établissements scolaires primaires et secondaires revient aux collectivités territoriales . L'instruction est actuellement obligatoire pour les enfants âgés de six à seize ans. En mars 2018, le président Emmanuel Macron annonce vouloir abaisser l'âge obligatoire de scolarisation à trois ans dès la rentrée 2019 ."),
                DefaultText("L'enseignement primaire se déroule en deux phases. L'école maternelle, qui accueille les très jeunes enfants, se donne pour but leur éveil, leur socialisation et la mise en place des outils fondamentaux que sont le langage et le nombre . Puis, vers l'âge de six ans, les enfants sont accueillis par l'école élémentaire, dont les premiers objectifs sont l'apprentissage de la lecture, de l'écriture et du calcul, et l'éducation civique ."),
                DefaultText("L'enseignement secondaire se déroule lui aussi en deux cycles. Le premier est dispensé au collège et aboutit au diplôme national du brevet . Le deuxième est dispensé au lycée et aboutit à des examens finaux et nationaux : le baccalauréat (professionnel, technologique ou général) et le certificat d'aptitude professionnelle (CAPA dans l'enseignement agricole) . Par ailleurs, près de 17 % des élèves de l'enseignement primaire et secondaire sont scolarisés dans des établissements privés , la plupart sous contrat d'association avec l'État et souvent confessionnels."),
                DefaultText("L'enseignement supérieur français présente la particularité de faire cohabiter les universités et le système des grandes écoles, où l'on entre généralement par concours à l'issue des classes préparatoires . Les enseignements supérieurs pour le brevet de technicien supérieur et les classes préparatoires aux grandes écoles sont dispensés dans des lycées ou dans des établissements privés. Tous les diplômes reconnus en France doivent être présent dans le répertoire national des certifications professionnelles."),
                DefaultText("La France a connu depuis la Libération un élargissement considérable de la scolarisation. En 1936, moins de 3 % d'une classe d'âge obtenait le baccalauréat ; ce pourcentage est passé à 30 % en 1985 et 60 % en 1995 . Néanmoins, cette démocratisation de l'enseignement ne supprime pas les inégalités sociales : 25 % des enfants d'ouvriers nés entre 1974 et 1978 sont diplômés de l'enseignement supérieur, contre 77 % des enfants de cadres . Ces inégalités sont encore plus fortes dans les grandes écoles : seuls 2,9 % des étudiants admis à l'École nationale d'administration en 2008 avaient un parent ouvrier ."),
                DefaultText("Selon le programme PISA de comparaison des systèmes éducatifs nationaux, les résultats du système éducatif français sont décevants par rapport aux autres États membres de l'OCDE , en particulier par l'accroissement des inégalités depuis l'enquête PISA de 2003. Malgré les plans de prévention, l'illettrisme touche 3,1 millions de personnes, soit 9 % de la population âgée de 18 à 65 ans ayant été scolarisée en France ."),
                DefaultText("L'origine sociale des élèves influe considérablement sur leurs résultats scolaires. En CE2, les élèves issus du quart le plus pauvre obtiennent en 2019 une note moyenne de 57 sur 100 en français et 58 en mathématiques, contre respectivement 87 et 85 pour ceux issus du quart le plus riche. Les inégalités s'accentuent après le collège, avec un taux d'accès en seconde générale ou technologique deux fois plus élevé pour les élèves issus de milieux favorisés que pour les autres ."),
                DefaultText("La première évaluation du ministère de l'Éducation nationale a révélé que la « continuité pédagogique » pendant le verrouillage au milieu de la pandémie de COVID-19 était positif. Selon l'enquête, sept enseignants sur dix et huit parents sur dix ont été jugés satisfaits."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),

                TitreH1(' VI ', ' Médias'),
                DefaultText("La pauvreté frappe 92 % de la population en 2017. Selon la Banque mondiale, 75 % de la population vivaient toujours sous le seuil international de pauvreté à 1,90 dollar par jour en 2019 — un taux nettement supérieur à la moyenne régionale de 41 % ."),
                DefaultText("Le pays occupe la quatrième place mondiale en termes de malnutrition chronique. Près d’un enfant de moins de 5 ans sur deux souffre d’un retard de croissance. En outre, Madagascar compte parmi les cinq pays où l’accès à l’eau est le plus difficile pour la population. Douze millions de personnes n’ont pas accès à l’eau potable, selon l’ONG WaterAid ."),
                DefaultText("Si les presses régionale, hebdomadaire et thématique se vendent bien en France , la presse quotidienne nationale d'information généraliste est peu diffusée hors de la capitale. Dès lors, les cinq principaux titres de cette catégorie (Le Figaro, Le Monde, Aujourd'hui en France, Libération et La Croix) ne vendent réunis que moins d'un million d'exemplaires chaque jour en 2010 ."),
                DefaultText("Depuis 1981 et la légalisation des « radios libres » , les stations de radio publiques gérées par Radio France sont concurrencées par des stations privées, souvent propriétés de grands groupes de médias . Dès lors, parmi les quatre premières stations de radio en audience cumulée en novembre-décembre 2009 (RTL, NRJ, France Inter et Europe 1 ), seule la troisième est publique. De même, depuis l'apparition de la première chaîne de télévision privée (Canal+) en 1984, plusieurs centaines de chaînes de télévision privées ont vu le jour, diffusées par le canal hertzien, par câble, par satellite ou plus récemment par la télévision numérique terrestre (TNT). Les trois principales chaînes sont TF1, France 2 et M6 , seule France 2 appartient au groupe public France Télévisions."),
                DefaultText("Quant à l'accès au réseau internet, il ne s'est vraiment démocratisé qu'au début des années 2000 . En décembre 2018, la France comptait 52,8 millions d'utilisateurs d'internet, soit une hausse de 13 millions par rapport à décembre 2012 ."),
                DefaultText("Entre 2002 et 2009, la France est passée de la 11e à la 43e place dans le classement de la liberté de la presse dans le monde établi par Reporters sans frontières . En 2019, la France était remontée à la 32e place sur 180 ."),
                DefaultText("En juillet 2020, une plateforme unique pour toutes les radios publiques et privées a été créée en tant que service numérique commun. Il a réuni des succursales de plusieurs radios, dont Lagardère News, Radio France, les radios du Groupe M6 et Les Indés Radios, où les utilisateurs pouvaient écouter tous les programmes en un seul endroit sans aucun coût ."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                
                TitreH1(' VII ', ' Sport'),
                DefaultText("La France est caractérisé par une tradition sportive ancienne et une grande variété de disciplines pratiquées à haut niveau. Le pays a un rôle prépondérant dans l'organisation du sport moderne et son palmarès, depuis la fin du e siècle. Avec un total de 840 médailles remportées (716 en été et 124 en hiver), la France est la cinquième nation la plus récompensée de l'histoire des Jeux olympiques. L'escrime et le cyclisme sont les disciplines dans lesquelles la France est la plus titrée (respectivement 44 et 41 titres olympiques après les Jeux de Vancouver en 2010) . Paris est la ville hôte des Jeux olympiques d'été en 1900 et en 1924 ; elle le sera pour une troisième fois en 2024 . La France a également accueilli les Jeux olympiques d'hiver à trois reprises : Chamonix en 1924, Grenoble en 1968 et Albertville en 1992 ."),
                DefaultText("Parmi ses autres distinctions notables, la France a remporté la Coupe du monde de football à deux reprises, la Coupe Davis à dix reprises ou encore le Tournoi des Six Nations à 25 reprises."),
                DefaultText("D'après le ministère des Sports, en 2010, 69 % des personnes de plus de 15 ans faisaient du sport au moins une fois par semaine en France. La marche, la natation et le vélo étaient les principales activités physiques déclarées. En 2016, l'ensemble des fédérations sportives françaises comptait 16 102 957 licenciés ; 37,5 % d'entre eux étaient des filles. En 2017, les sports les plus pratiqués en France étaient : le football (2 135 193 licenciés, 5,7 % de filles), le tennis (1 052 127 licenciés, 29,1 % de filles), l'équitation (673 026 licenciés, 82,9 % de filles), le judo (552 815 licenciés, 26,7 % de filles), le basketball (513 727 licenciés, 36 % de filles), le handball (513 194 licenciés, 35,8 % de filles) et le golf (407 569 licenciés, 27,8 % de filles) . Près de sept millions de Français pratiquent le ski chaque hiver, le plus souvent en dehors de toute organisation sportive . Le domaine skiable français était en 2015 le domaine le plus fréquenté du monde, devant ceux des États-Unis et de l'Autriche ."),
                CustomImageCard("assets/260px-France_champion_of_the_Football_World_Cup_Russia_2018.jpg", "Les joueurs de l'équipe de France de football soulevant, le 15 juillet 2018 à  Moscou, le trophée de la 21e édition de la Coupe du monde"),
                DefaultText("En 2013, la dépense sportive nationale s'établissait à 38,1 milliards d'euros (la moitié étant à la charge de l'administration publique), soit 1,8 % du PIB. En 2015, le secteur sportif privé en France employait 124 286 salariés. Chaque année, le ministère des Sports délivre environ 12 000 diplômes sportifs, dont près de 8 000 BPJEPS ."),
                DefaultText("Le tournoi de tennis international de Roland-Garros, à Paris, et le Tour de France cycliste sont des événements annuels importants, tout comme peuvent l'être des événements ponctuels tels que l'Euro de football de 2016."),
                DefaultText("La France s'intéresse également de plus en plus à l'e-sport. En 2016, le gouvernement Valls II crée l'association France Esports. En 2018, 5 millions de Français avaient déjà regardé au moins une compétition d'e-sport et 930 000 y avaient déjà participé . Elle possède l'une des plus performante structure e-sport d'Europe et du monde avec la Team Vitality."),
                DefaultText("Outre les couleurs du drapeau, pour les fédérations sportives françaises, le coq est aussi utilisé comme symbole, mais ce n’est pas un symbole officiel[réf. souhaitée]."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                
                TitreH1(' VIII ', ' Engagement associatif, syndical et politique'),
                DefaultText("Si les taux de participation aux élections diminuent, la participation protestataire, en revanche, se développe . En 2008, 42 % des Français ont participé à une manifestation, contre 25 % en 1981 . En comparaison des autres pays développés, la France est souvent vue comme un pays où les manifestations et les grèves sont fréquentes ."),
                DefaultText("Mais cette participation ponctuelle à des événements contestataires ne se traduit pas, tant s'en faut, par un engagement important dans les partis politiques . Quant au taux de syndicalisation (8 %), il est le plus faible des pays riches, même s'il est plus important dans le secteur public . En revanche, les Français sont très impliqués dans le milieu associatif : 14 millions de bénévoles sont membres de plus d'un million d'associations , qui bénéficient du statut accordé par la loi du 1er juillet 1901 ."),
                
              ],
            ),
          ),
        ],
      ),
    );
  }
}