import 'package:flutter/material.dart';
import 'package:flutter_app/texte/texte.dart';
class franceStat extends StatelessWidget {
  const franceStat({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
        padding: EdgeInsets.all(10.0),
        child: ListView(physics: BouncingScrollPhysics(), children: [
          ResumeContainer("L'économie de la France est une économie sociale de marché fondée sur la propriété privée. Il y a une intervention étatique relativement forte depuis la fin de la Seconde Guerre mondiale, bien que celle-ci soit remise en cause depuis les années 1980 . L'économie française est principalement tournée vers les services . Les prélèvements obligatoires représentent 46,2 % du PIB en 2017, soit le taux le plus élevé parmi les pays membres de l'OCDE , et les dépenses publiques totalisent 56,8 % du PIB en 2015, soit le deuxième taux le plus élevé de l'OCDE ."),
          new Container(
            margin: EdgeInsets.only(top: 50),
            padding: EdgeInsets.all(10),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                TitreH1('  I  ', ' Revenus de la population et développement humain'),
                DefaultText("En 2018, il y avait 2,147 millions de millionnaires (en dollars américains) en France, soit 5 % des millionnaires dans le monde . Selon le magazine Forbes, il y avait, cette même année, 39 milliardaires en France, ce qui fait de la France le 9è pays au monde avec le plus de milliardaires ."),
                DefaultText("En 2014, selon le World Inequality Database, en France, les 1 % les plus aisés captaient 10,8 % du revenu national avant impôt (ce chiffre était de 11,0 % en 2000, 11,5 % en 1960 et 20,1 % en 1920), les 10 % les plus aisés en captaient 32,6 % (ce chiffre était de 33,1 % en 2000, 37,7 % en 1960 et 47,3 % en 1920), les 50 % les plus pauvres en captaient 22,5 % (ce chiffre était 21,5 % en 2000, 18,6 % en 1960 et 14,6 % en 1920). Les inégalités de revenus en France au e siècle sont donc plus faibles qu'au e siècle et, sur le long terme, ont tendance à se réduire ."),
                DefaultText("Les revenus des Français et leur pouvoir d'achat ont augmenté durant l'ensemble du e siècle et des années 2000 , mais de façon inégale au sein de la population, ce qui a accru les inégalités économiques entre ménages . Depuis 2014, le pouvoir d'achat du revenu disponible des ménages augmente de manière continue en France, quoique relativement lentement : +1,2 % en 2014, +0,9 % en 2015, +1,8 % en 2016 et +1,3 % en 2017. En 2017, le taux d'épargne (en % du revenu disponible brut) était de 14,3 % et le taux d'épargne financière (en % du revenu disponible brut) était de 4,4 % ."),
                DefaultText(
                    "En France, le salaire mensuel net moyen s'élevait en 2015 à 2 250 euros . En 2016, selon l'INSEE, le salaire mensuel net médian était de 1 680 euros et le revenu disponible brut par habitant était de 1 402 euros (+1 % par rapport à 2008) . En 2015, le revenu disponible moyen des ménages était de 36 300 euros et le revenu disponible médian des ménages était de 30 040 euros . En France, à métier, entreprise et fonction équivalentes, l'écart salarial entre femmes et hommes est de 2,7% ."),
                DefaultText(
                    "En 2015, en France métropolitaine, le niveau de vie médian de la population s'élève à 20 300 euros annuels, soit un niveau légèrement plus élevé qu'en 2014 en euros constants. Le seuil de pauvreté monétaire, qui correspond à 60 % du niveau de vie médian de la population, s'établit à 1 015 euros mensuels ; 14,2 % de la population vit sous ce seuil de pauvreté, un des niveaux les plus bas de l'Union européenne. Les chômeurs ont le plus fort taux de pauvreté (37,3 %). De 1970 à 1990, le taux de pauvreté s'est fortement réduit (-4,1 points) sous l'effet notamment de l'amélioration de la situation relative des retraités, dont le taux de pauvreté a diminué de plus de moitié grâce à l'amélioration de leur retraite et au minimum vieillesse. Depuis 1996, les évolutions du taux de pauvreté sont de moindre amplitude. Ce taux a diminué de 1,9 point entre 1996 et 2004, est remonté entre 2004 et 2011 (+1,8 point), notamment du fait de la crise de 2008, et depuis évolue peu ."),
                CustomImageCard("assets/World_Income_Gini_Map_(2013).svg.png", "Inégalité des revenus (2013) au sein des pays, mesuré par le coefficient de Gini : 0 correspond à une égalité parfaite (toutes les personnes ont les mêmes richesses), et 100 à une inégalité totale (où une personne posséderait tout). Les pays en rouge sont plus inégalitaires que les pays en vert."),
                DefaultText(
                    "En 2017, selon les Nations unies, l'indice de développement humain (IDH) de la France était de 0,901, la plaçant au 24e rang du classement mondial de l'IDH. À titre de comparaison, en 1990, l'IDH de la France s'élevait à 0,779 . Selon la Banque mondiale, le PIB par habitant en dollars courant de la France s'élevait à 38 467 dollars en 2017, soit le 24e PIB par habitant le plus élevé au monde . L'indice de Gini, qui mesure les inégalités, était calculé à 32,7 pour la France en 2015 ."),
                DefaultText(
                    "Au premier trimestre 2012, l'INSEE dénombrait 141 500 SDF en France . En outre, 800 000 personnes n'ont pas de domicile personnel ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),

                TitreH1(' II ', ' Emploi'),
                DefaultText("Si la France a connu durant les Trente Glorieuses une situation proche du plein emploi — au cours des seules années 1960, l’économie française a créé 1,6 million d’emplois —, elle fait face depuis la fin des années 1970 à une situation de chômage élevé, malgré des fluctuations qui ont fait espérer le retour du plein emploi . Le chômage touche particulièrement les jeunes, les moins diplômés et les étrangers. Les chômeurs de longue durée représentent un tiers de l'ensemble des chômeurs et sont ceux pour qui la réinsertion est souvent la plus difficile . Selon l'Insee, le taux de chômage français s'est établi en août 2019 à 8,5 % (son niveau le plus bas depuis 2009) . Au deuxième trimestre de 2019, le taux de chômage longue durée était de 3,2 % . Selon l'économiste Éric Heyer, il y aurait eu 150 000 emplois non pourvus en France en 2017 ."),
                DefaultText("En moyenne, en 2017, 29,3 millions de personnes de 15 à 64 ans en France (hors Mayotte) étaient actives, soit 71,5 % de cette tranche d'âge. Parmi elles, 26,5 millions avaient un emploi et 2,8 millions étaient au chômage au sens du Bureau international du travail (BIT) ; 11,7 millions étaient inactives, c'est-à-dire ne travaillaient pas et ne recherchaient pas activement un emploi ou ne sont pas disponibles pour en occuper un. En 2017, le taux d'emploi en France était de 64,7 % et le taux d'activité était de 71,5 % . En 2017 comme en 2016, 18,8 % des personnes ayant un emploi travaillaient à temps partiel ."),
                DefaultText("À la fin de l'année 2017, le secteur privé en France employait 19,27 millions de salariés (+1,3 % par rapport à l'année 2016) ."),
                DefaultText(
                    "Les salariés représentaient 88,4 % des actifs occupés en France en 2017 : 84,6 % sont en contrat à durée indéterminée (CDI) ou fonctionnaires, 10,8 % en contrat à durée déterminée (CDD), 3,0 % en intérim et 1,6 % en apprentissage ."),
                DefaultText(
                    "En 2017, les professions intermédiaires et les cadres représentaient 43,7 % des actifs occupés, proportion en légère hausse sur un an. La part des ouvriers, qui avait baissé, de façon quasi ininterrompue, de près de 10 points depuis le début des années 1980, a augmenté légèrement en 2017 (+ 0,5 point, à 20,8 %) ; celle des employés (27,2 %) a reculé légèrement (– 0,2 point), dans la lignée du repli observé depuis une dizaine d'années. Les ouvriers et employés non qualifiés représentaient en 2017 un actif occupé sur cinq ."),
                DefaultText(
                    "En 2017, 5,664 millions de personnes travaillaient dans la fonction publique en France. 62,5 % des personnes travaillant dans la fonction publique sont des femmes et 37,5 % sont des hommes. Les statuts dans la fonction publique sont variés, il y a 67,8 % de fonctionnaires, 17,9 % de contractuels, 5,5 % de militaires et 2,5 % de contrats aidés (les 6,3 % restant ont un autre statut) ."),
                DefaultText(
                    "En 2017, en France, selon l'OCDE, le temps de travail hebdomadaire moyen des hommes était de 38,4 heures (soit un chiffre en légère baisse depuis les années 1980, il était de 40,1 heures en 1983) et celui des femmes était de 33,8 heures (également en légère baisse depuis les années 1980, il était de 35,5 heures en 1983). En moyenne, les Français ont travaillé 36,1 heures par semaine en 2017, un chiffre extrêmement stable depuis 1996 (il faut remonter à 1995 pour avoir un temps de travail hebdomadaire moyen supérieur à 37,0 heures) ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),

                TitreH1(' III ', " Principaux secteurs d'activité"),
                DefaultText("L'économie française est largement tournée vers le secteur des services. Selon le World Factbook de la CIA, en 2017, les services composaient 78,8% du PIB de la France, l'industrie 19,5% et l'agriculture 1,7% . Selon l'INSEE, en 2018, 76,1% de la population en emploi travaillait dans le secteur tertiaire, 13,3% dans le secteur de l'industrie, 6,7% dans le secteur de la construction et 2,5% dans le secteur de l'agriculture ."),
                DefaultText("Par branche d'activité, la production en euros courants en 2018 en France était, selon l'INSEE, de 2 215,2 milliards d'euros pour les services marchands (1 187,7 milliards d'euros en valeur ajoutée), 939,4 milliards d'euros pour l'industrie manufacturière (280,2 milliards d'euros en valeur ajoutée), 615,8 milliards d'euros pour les services non marchands (467,5 milliards d'euros en valeur ajoutée), 303,7 milliards d'euros pour la construction (117,4 milliards d'euros en valeur ajoutée) et 90,0 milliards d'euros pour l'agriculture (38,2 milliards d'euros en valeur ajoutée) ."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-A ', ' Agriculture et agroalimentaire'),
                DefaultText("La France a connu, comme d'autres pays industrialisés, des phénomènes d'exode rural et de chute de l'emploi agricole , même si ce dernier reste proportionnellement plus important que dans les autres pays d'Europe occidentale . L'agriculture française a été considérablement modernisée et mécanisée dans la seconde moitié du e siècle , notamment au moyen de la politique agricole commune (PAC) . La spécialisation régionale de la France par type de production s'accentue , et certaines appellations d'origine de produits agricoles (transformés ou non) sont préservées grâce au système AOC, qui prend en considération un terroir , c'est-à-dire un savoir-faire agricole populaire et historique attaché à un territoire . La France se tourne progressivement vers l'agriculture biologique depuis la fin du XXè siècle. Le label Agriculture biologique est créée en 1985 ; depuis 2009, il est aligné sur les critères du label bio de l'Union européenne."),
                CustomImageCard("assets/220px-Épône_-_récolte_du_maïs01.jpg", "Une récolte de maïs à Épône, près de Paris."),
                DefaultText("La France comptait 451 606 exploitations agricoles sur son territoire métropolitain en 2013. Elle en comptait 1,02 million en 1988. La superficie moyenne des exploitations agricoles est de 61 hectares. Le nombre d'exploitations d'agriculture biologique était de 25 000 en 2013 ."),
                DefaultText("En 2015, il y avait 885 400 exploitants agricoles en France (-8 % par rapport à 2010). L'âge moyen des chefs d'exploitation, coexploitants et associés est de 51 ans. 30 % des actifs permanents agricoles sont des femmes ."),
                DefaultText("La production agricole française se chiffre pour l'année 2017 à 78,8 milliards d'euros en incluant les services et les subventions sur les produits, soit 3,5 % du PIB français, contre quelque 7 % en 1980. La France a dégagé en 2016 un excédent commercial agroalimentaire (produits bruts et transformés) de 6,1 milliards d'euros . L'agriculture française est généreusement soutenue par l'Union européenne. Elle a bénéficié en 2015 de 8,95 milliards d'euros de financement de la part de la PAC, soit 21 % de son budget total ."),
                DefaultText("La France est le premier producteur agricole de l'Union européenne : elle représentait, en 2016, 17 % de la production totale de l'UE . La France est le premier producteur européen de viande bovine, d'œufs, de surimi, de céréales et de sucre de betteraves. Elle est le sixième producteur mondial de beurre et le premier exportateur mondial de pommes de terre. Elle est également le deuxième producteur mondial de vin, le deuxième producteur européen de lait et le troisième producteur européen de fruits et de légumes ."),
                DefaultText("Selon l'ONUAA (données 2018), la France est le 8e producteur mondial d'abricots, le 8e producteur mondial d'artichauts, le 5e producteur mondial de blé, le 2e producteur mondial de céréales mélangées, le 6e producteur mondial de céréales entières, le 8e producteur mondial de champignons et truffes, le 1er producteur mondial de chanvre, le 8e producteur mondial de fibres de chanvre, le 9e producteur mondial de choux-fleurs et brocolis, le 4e producteur mondial de colza, le 7e producteur mondial d'épinards, le 7e producteur mondial de fèves sèches, le 7e producteur mondial de fruits à noyau, le 8e producteur mondial de graines de lin, le 9e producteur mondial de graines de tournesol, le 2e producteur mondial de haricots verts, le 8e producteur mondial de kiwis, le 1er producteur mondial de fibres et étoupes de lin, le 8e producteur mondial de maïs frais, le 9e producteur mondial de moutarde, le 10e producteur mondial de myrtilles, le 8e producteur mondial de noisettes, le 9e producteur mondial de noix, le 4e producteur mondial d'oeuillettes, le 2e producteur mondiald'orge, le 5e producteur mondial de poireaux, le 3e producteur mondial de pois frais, le 7e producteur mondial de pois secs, le 9e producteur mondial de pommes, le 8e producteur mondial de pommes de terre, le 2e producteur mondial de racines de chicorée, le 5e producteur mondial de raisins, le 3e producteur mondial de sarrasin, le 2e producteur mondial de betteraves à sucre et le 3e producteur mondial de triticales ."),
                DefaultText(
                    "Les émissions de gaz à effet de serre par l'agriculture française ont significativement diminué au cours des dernières années, passant de 76 198 équivalent CO2 en 1995 à 69 353 équivalent CO2 en 2016, soit une baisse d'environ 10 % ."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-B ', ' Tourisme'),
                DefaultText("Grâce à la richesse de ses paysages naturels et de son patrimoine culturel, la France est le pays le plus visité au monde par les touristes étrangers avec près de 90 millions de visites en 2018 . Près de 70 millions des touristes internationaux venant en France sont en provenance d'Europe ."),
                CustomImageCard("assets/170px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg", "La Joconde est le plus célèbre des tableaux , en exposition permanente au musée du Louvre, le musée le plus visité du monde ."),
                DefaultText("Les recettes liées au tourisme international en France s'élèvent pour l'année 2017 à 69,89 milliards de dollars US. Ainsi, la France est le deuxième pays aux recettes touristiques les plus élevées, derrière les États-Unis et devant l'Espagne et la Thaïlande . En 2015, la consommation touristique intérieure s'élève à 160 milliards d'euros, soit 7,2 % du PIB de la France ."),
                DefaultText("En 2017, Paris est la 3e ville la plus visitée au monde, avec 17,44 millions de touristes internationaux ; elle est devancée par Londres (19,83 millions de touristes) et Bangkok (20,05 millions de touristes) . Cependant, si l'on considère Paris en tant qu'agglomération (comme c'est le cas pour Londres et Bangkok dans le classement car, dans leurs cas, la ville-centre se confond avec l'agglomération contrairement à Paris), le nombre de touristes internationaux monte à 33,8 millions . Le musée du Louvre est le musée le plus visité au monde (10 millions de visiteurs en 2018) et Notre-Dame de Paris est le monument le plus visité d'Europe (14 millions de visiteurs en 2018) ."),
                DefaultText("Les motifs de ce tourisme sont variés : il s'agit tout à la fois d'un tourisme culturel (notamment à Paris) , balnéaire (notamment sur la Côte d'Azur) , naturel , d'affaires (Paris est la première destination mondiale pour ce type de tourisme) , de loisirs (Disneyland Paris est de loin le parc d'attractions le plus fréquenté d'Europe) et de sports d'hiver (dans les Alpes du Nord notamment) . Les sites touristiques payants les plus fréquentés sont dans leur majorité situés en Île-de-France (Disneyland Paris, musée du Louvre, tour Eiffel, château de Versailles…) ; quelques sites de région attirent également de nombreux touristes, comme les châteaux de la Loire, le mont Saint-Michel, Rocamadour, le château du Haut-Kœnigsbourg, le musée Unterlinden de Colmar, le centre PompidouMetz ou le parc du Futuroscope ."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-C ', ' Commerce et artisanat'),
                DefaultText("Depuis les années 1970, le secteur du commerce a été bouleversé par l'irruption de la grande distribution, qui représente les deux tiers des dépenses alimentaires des Français en 2008 . Par conséquent, de nombreux petits commerces ont disparu, même si l'on assiste en 2009 à une timide reprise, notamment dans les centres-villes . La puissance de quelques grandes entreprises de la grande distribution — Carrefour par exemple est le deuxième groupe mondial du secteur — leur permet d'imposer, dans une certaine mesure, des prix bas aux producteurs . Malgré la concurrence des entreprises industrielles, l'artisanat de son côté est parvenu à conserver une place importante dans l'économie française ."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-D ', ' Industrie'),
                DefaultText("La France est la quatrième puissance industrielle mondiale. Malgré la tertiarisation de l'économie française, les entreprises industrielles représentaient 12,6 % du PIB et 96,5 % des exportations françaises en 2014 ."),
                ListGrid("assets/Rafale_C_(7782446466).jpg", "Dessault Rafale", "assets/240px-Leclerc_p1040617.jpg", "Char Leclerc"),
                DefaultText("Son industrie est caractérisée par des évolutions contrastées : à côté d'industries modernes et dynamiques, qui font de la France un des leaders mondiaux dans de nombreux domaines (automobile, aéronautique, aérospatiale, agroalimentaire, électronique, nucléaire civil, pharmacie, cosmétique, luxe…) , de nombreuses industries traditionnelles (mines, textile, bois, chaussure, construction navale, sidérurgie…) voient leurs effectifs et leurs chiffres d'affaires chuter , obligeant des régions entières (Nord-Pas-de-Calais et Lorraine notamment) à une douloureuse reconversion . À la décentralisation industrielle des années 1960, qui a permis le développement de nombreuses villes de l'ouest et du sud du pays , a succédé une période de croissance faible de la production industrielle , qui s'explique parfois par des délocalisations vers des pays à la main-d'œuvre peu onéreuse ."),
                DefaultText("Même si la production se fait de plus en plus souvent à l'étranger, les entreprises françaises restent prédominantes dans de nombreux domaines , certaines occupent la première place du marché mondial dans leur domaine (par exemple L'Oréal dans les cosmétiques ou Michelin dans les pneumatiques ). En 2018, 28 entreprises françaises figurent dans le classement Global 500 du magazine Fortune, ainsi la France est le cinquième pays avec le plus d'entreprises dans le classement, derrière les États-Unis, la Chine, l'Allemagne et le Japon. Les six entreprises françaises figurant dans le top 100 sont Axa (rang 27), Total (rang 28), BNP Paribas (rang 44), Carrefour (rang 68), Crédit agricole (rang 82) et EDF (rang 94) ."),
                CustomImageCard("assets/Charles_De_Gaulle_PascalSubtil_2.jpg", "Porte-avions Charle De Gaulle"),
                DefaultText("L'industrie française de l'armement représente 165 000 emplois en 2013 . Elle couvre un large spectre avec notamment la construction navale (Naval Group), l'aviation militaire (Dassault Aviation, Airbus, Safran) et les systèmes d'armement (MBDA, Thales), la fabrication de véhicules blindés (Nexter, Arquus). L'ensemble du complexe militaro-industriel est coordonné par la direction générale de l'Armement (DGA). La France est en outre un acteur mondial majeur dans le secteur de la défense : les exportations d'armement de la France atteignaient 16 milliards d'euros en 2015 et plus de 20 milliards d'euros en 2016."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-E ', ' Énergie'),
                DefaultText("Après la disparition complète de la production française de charbon en 2005 , le pétrole, le gaz et surtout l'électricité sont les principales énergies consommées en France . Si la France ne produit plus de pétrole brut que de façon marginale , les treize raffineries implantées sur le territoire permettent de satisfaire plus de 90 % de la demande nationale . Le groupe français Total, qui possède des concessions dans le monde entier, est la sixième entreprise mondiale et la cinquième du secteur . La part du gaz dans la consommation énergétique française a fortement augmenté depuis les années 1970 , mais il s'agit à 97 % de gaz importé, notamment de Russie, d'Algérie et de la mer du Nord . En revanche, la France produit plus d'électricité qu'elle n'en consomme , notamment grâce à 59 réacteurs nucléaires (le second parc mondial après le parc américain) qui produisaient en 2013 près de 74 % de l'électricité du pays , permettant à l'électricité française d'être très peu carbonée, mais dont le bilan environnemental est l'objet de débats . Quant aux énergies renouvelables, leur part dans la production électrique française augmente et s'établit en 2013 à près de 17 % , en grande partie grâce à l'hydroélectrique."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-F ', ' Une nation avec un programme spatial autonome dans un cadre européen'),
                DefaultText("Outre l'aviation civile, le général de Gaulle fait de l'espace une priorité nationale pour préserver l'indépendance de la France . La plus importante agence spatiale en Europe, le CNES est créé en 1961, et permet à la France de devenir en 1965 la troisième nation, après l'Union soviétique (Spoutnik 1, 1957) et les États-Unis (Explorer 1, 1958), à envoyer un satellite dans l'espace par ses propres moyens ; la fusée Diamant A envoie le satellite Astérix A1 depuis la base d'Hammaguir (Algérie). En 1973, la France propose aux pays européens un lanceur commun, Ariane , exploité par l'Agence spatiale européenne depuis 1975 depuis la sol français, au Centre Spatial Guyanais. Le programme continue depuis et constitue un important succès technologique et commercial. En 2011, le lanceur russe Soyouz décolle pour la première fois du sol français, marquant le début d'une collaboration très poussée avec le secteur spatial russe."),
                DefaultText("Enfin, la France participe au projet Galiléo est le système européen de positionnement par satellite visant à concurrencer le système américain GPS , ainsi qu'à diverses sondes d'exploration interplanétaires (Rosetta, BepiColombo, Mars Express, etc...)."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-G ', ' Recherche'),
                DefaultText("La France consacre une part moyennement élevée de son PIB à la recherche et développement (2,02 % en 2009 ), mais ces dépenses sont davantage financées par le secteur public (41 % en 2008 ) et consacrées à la recherche fondamentale que dans les autres pays de l'Union européenne et a fortiori de l'OCDE. Si la recherche française est à l'origine de nombreuses découvertes et a été récompensée à de multiples reprises (voir infra), le nombre de brevets déposés par des entreprises françaises est relativement faible , d'autant que les relations entre les entreprises privées et la recherche publique sont souvent jugées médiocres . En 2015, environ 280 000 chercheurs travaillaient en France, dont 170 000 en entreprise et 110 000 dans la fonction publique . Ces derniers sont regroupés dans des universités ou dans des établissements publics comme le CNRS (généraliste), le CEA (nucléaire), l'INRIA (informatique et mathématiques appliquées), l'INRA (agronomie). Parmi ces établissements, le LETI se positionne comme l'un des principaux laboratoires en microélectronique et nanotechnologies dans le monde , jouxtant le complexe Minatec, principal centre de recherche en Europe sur les nanotechnologies."),
                DefaultText("La France accueille par ailleurs sur son territoire de grands instruments de recherche internationaux comme l'European Synchrotron Radiation Facility, l'Institut Laue-Langevin ou l'Institut de radioastronomie millimétrique et demeure un acteur majeur du CERN. Depuis 2002, la plupart de ces centres de recherche sont organisés en réseaux avec des universités et des entreprises, pour former des pôles de compétitivité (71 en 2007 )."),
                Divider(
                  height: 10,
                  color: Colors.white,
                ),
                TitreH2(' III-H ', ' Finance et assurance'),
                DefaultText("Le secteur bancaire français a longtemps été caractérisé par sa faible concentration, par la ferme réglementation qui l'encadrait et par la part importante du secteur public, mais cette situation a changé au cours des années 1990 et 2000. Les banques françaises BNP Paribas, Société générale et Crédit agricole se placent respectivement aux quatrième, neuvième et dixième places mondiales du secteur en 2009 . Le secteur des assurances occupe également une place importante dans l'économie française, Axa étant la première compagnie d'assurance européenne ."),
                DefaultText("La bourse de Paris, filiale d'Euronext depuis 2000, est le marché officiel des actions en France. L'indice CAC 40 est un indice pondéré en fonction de la capitalisation boursière flottante qui reflète la performance des 40 actions les plus importantes et les plus activement échangées cotées sur Euronext Paris. Au 30 septembre 2020, la capitalisation boursière totale des composantes du CAC 40 était de 1 529 milliards d'euros. La capitalisation boursière médiane des composantes de l'indice était de 23,77 milliards d'euros, et LVMH, Sanofi et Total étaient les trois plus grosses entreprises de l'indice ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),

                TitreH1(' IV ', " Place de la France dans l'économie mondiale"),
                DefaultText("En 2018, selon le FMI, le PIB nominal de la France s'élevait à 2 775,25 milliards de dollars ; selon ce critère, la France est la 7e économie mondiale . Selon le Crédit suisse, la France disposait en 2018 d'une richesse totale (en) estimée à 13 883 milliards de dollars, faisant de la France le 6e pays la plus riche du monde et le 3e plus riche d'Europe selon ce critère ."),
                DefaultText("D'après le Global Competitiveness Report 2018 publié par le Forum économique mondial, la France est la 17e (sur 140) économie la plus compétitive du monde (gain d'une place par rapport à l'année 2017). Le rapport salue la qualité des infrastructures françaises et le haut niveau de santé publique, mais il reproche à la France son nombre trop important de régulations, les faibles compétences numériques de sa main d'œuvre, le nombre trop faible d'enseignants à l'école, le nombre trop élevé de barrières non-tarifaires, le manque de flexibilité de son marché du travail et le niveau trop élevé d'imposition . Dans le 2019 Index of Economic Freedom de l'Heritage Foundation, qui mesure le degré de liberté économique de chaque pays dans le monde, la France n'obtient que la 71e place (sur 186 pays classés) à cause du niveau élevé de ses dépenses publiques, des régulations rigides de son marché du travail et de son important taux de prélèvements obligatoires ."),
                DefaultText("L'économie française est fortement extravertie , notamment vis-à-vis de ses partenaires européens (65 % des exportations françaises ). Cette situation est en partie liée à l'épuisement ou à l'insuffisance des ressources minières et énergétiques du pays, qui l'obligent à importer , et à la taillerelativement réduite de ce pays. Mais elle s'explique également par l'importance des exportations. Selon l'OMC, en 2017, la France est le 8e exportateur(535 milliards de dollars d'exportations) et le 6e importateur (625 milliards de dollars d'importations) mondial de marchandises. En ce qui concerne les services, elle en est le 4e exportateur (248 milliards de dollars d'exportations) et 4e importateur (240 milliards de dollars d'importations) mondial ."),
                DefaultText(
                    "Néanmoins, le commerce extérieur de la France connaît d'importantes difficultés. Depuis 2004, la France connaît un déficit de sa balance commerciale, de plus en plus creusé (- 75,4 milliards de dollars en 2009 ), une situation qui s'explique en partie par le niveau élevé de l'euro face au dollar . Entre 1990 et 2006, la part de marché mondiale de la France dans les exportations de marchandises est passée de 6,3 à 4,1 % ; la France n'est plus en 2009 que le cinquième importateur et le sixième exportateur mondial . Selon Eurostat, cette dégradation du commerce extérieur français serait en partie due à une augmentation des coûts salariaux horaires . Le solde commercial continue d'être déficitaire en 2017 : le solde des biens et services enregistre un déficit de 38,3 Md€ (26,8 Md€ en 2016). Cette dégradation reflète principalement la dynamique de la demande intérieure française portée par la reprise de la consommation des ménages et de l'investissement des entreprises qui ont soutenu les importations de biens : +6,8 % à 535,5 Md€ après +0,1 % en 2016. Par ailleurs, la facture énergétique (39 Md€) s'alourdit en 2017 et pèse fortement sur la balance commerciale, équivalant à 63 % du déficit total ."),
               

              ],
            ),
          ),
        ]));
  }
}
