import 'package:flutter/material.dart';
import 'package:flutter_app/texte/texte.dart';
class chineStat extends StatelessWidget {
  const chineStat({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
        padding: EdgeInsets.all(10.0),
        child: ListView(physics: BouncingScrollPhysics(), children: [
          new Container(
            padding: EdgeInsets.all(10),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                TitreH1('  I  ', ' Histoire économique'),
                DefaultText("On estime que la Chine a été la première puissance économique mondiale durant la majeure partie des vingt derniers siècles de l'histoire. Jusqu'au XVIIIè siècle et la révolution industrielle, c'est également en Chine qu'on trouvait le niveau de vie le plus élevé de la planète ."),
                DefaultText("La Chine, première civilisation à utiliser le papier monnaie, a une longue histoire de relations économiques internationales. On retiendra quelques points de repères utiles :"),
                ListeWithTextGras("-", "La dynastie des Yuan a organisé un système de routes et de poste efficaces, contribuant à la modernisation de l'économie chinoise."),
                ListeWithTextGras("-", "Au début de l'ère Ming, les flottes de l'amiral Zheng He ont renforcé les liens existant déjà sur la route des épices, entre l'Inde, la côte africaine orientale, l'Indonésie et supposément l'Australie ainsi que les Amériques (avant les Européens, cf. cartes de l'Amiral de cette époque)."),
                ListeWithTextGras("-", "À la suite d'une période de repli sous les Ming, la dynastie Qing a vu son déficit économique s'accroître avec l'arrivée des colonisateurs occidentaux. Au milieu du XIXè siècle, l'économie chinoise a été dans sa plus grande partie asservie au commerce de l'opium pour les intérêts des colonisateurs, précipitant le pays dans un chaos économique et politique."),
                ListeWithTextGras("-", "Le règne de Mao Zedong a été synonyme d'une nouvelle période de quasi-autarcie économique, en dehors de certains échanges avec les pays de la sphère communiste."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),

                TitreH1(' II ', " Libéralisation de l'économie"),
                CustomImageCard("assets/chine/Hongxing_Road.jpg", "Compte tenu de la modernisation du pays, la société civile chinoise évolue à grande vitesse et adopte les nouveaux modes de consommation à l'instar des pays développés."),
                DefaultText("Le Parti communiste chinois définit l'économie de la Chine comme une « économie socialiste de marché », une forme de « socialisme aux caractéristiques chinoises ». De 1978 à 1989, le gouvernement chinois a mené une politique de réformes économiques importantes, faisant passer la Chine d'une économie planifiée de type soviétique à un « socialisme de marché », conservant la structure rigide de contrôle par le Parti communiste chinois, ce qui l'a fait appeler « l'atelier du monde ». Dans ce but, la collectivisation de l'agriculture a laissé place à un système de responsabilisation individuelle des terres. Les cadres locaux ont acquis plus de marge de manœuvre, des gérants ont été introduits dans les secteurs industriels, permettant l'essor de nombreuses petites entreprises, alors nommées getihu (个体户). Cette politique a permis d'attirer de nombreux commerçants et investisseurs étrangers. Le contrôle des prix a été relâché, à l'exception notable de produits de première nécessité pour les paysans."),
                DefaultText("En 1992, l'appellation officielle du système devient « économie de marché socialiste » et le changement d'adjectifs marque le début du changement de nature de classe de l'État. Le secteur public commence à se noyer dans l'océan de l'économie marchande et passe de 73 % de la production industrielle en 1988 à 35 % en 1992. Cela a permis le passage d'une économie planifiée à une économie mixte et la redécouverte des fondements du libéralisme économique, tout en sauvegardant le communisme officiel du régime. Dans ce nouveau système économique, les entreprises publiques ou danwei ont du mal à trouver leur place et rencontrent de plus en plus de difficultés. Leurs pertes ont atteint le chiffre record de 102,6 milliards de yuans (12,75 milliards de dollars américains) en 2005, soit une augmentation de 56,7 % en base annuelle, selon les chiffres du Bureau d'État des statistiques (BES). Sur les deux premiers mois de 2006, les pertes des entreprises publiques ou contrôlées par l'État atteignent déjà 26,2 milliards de yuans, soit 3,25 milliards de dollars américains. L'augmentation des coûts de production, un système de fixation des prix inefficace, la surcapacité et d'importantes lacunes d'ordre technologique sont les principales causes de cette situation, selon Jiang Yuan, statisticien au Bureau d'État des statistiques [réf. nécessaire] "),
                DefaultText("Le gouvernement met résolument entre parenthèses l'égalité des classes durant cette période, menée par le mot d'ordre de Deng Xiaoping : « Enrichissez-vous ! » L'enrichissement personnel (individualisme) et la consommation (soutenue par des politiques néokeynésiennes dès 1997) sont devenus de nouveaux moteurs économiques, accompagnés par une professionnalisation progressive des techniques de gestion, destinées à améliorer la productivité (division du travail). Le gouvernement a également œuvré pour attirer des capitaux étrangers, sources cruciales de développement économique : les zones économiques spéciales (ZES), exemptes de taxes, ont été créées à cet effet, étendues peu à peu à tout le littoral. Grâce à l'introduction du libre-échange, on observe qu'un quadruplement du produit intérieur brut (PIB) s'est produit depuis 1978. Les incitations par taxes préférentielles sont également à l'origine d'incitations fiscales à produire en Chine, que ce soit pour l'export ou pour le marché intérieur d'un milliard trois cents millions d'individus. La république populaire de Chine tente d'harmoniser le système de taxes et règlements pratiqués sur les entreprises, aussi bien chinoises qu'étrangères. Ainsi, les taxes préférentielles dont bénéficient les exportateurs dans les zones économiques spéciales et les villes côtières sont l'objet d'une révision. Les exportations chinoises vers les États-Unis représentaient 125 milliards de dollars américains en 2002, tandis que les importations américaines atteignaient 19 milliards. Ce déséquilibre est attribué de façon récurrente par les États-Unis à un taux de change jugé défavorable entre le yuan et le dollar américain. En revanche, pour la Chine, une réévaluation du yuan telle que la souhaitent les États-Unis créerait une inflation très importante, elle-même génératrice de tensions sociales internes. Le 21 juillet 2005, la Banque populaire de Chine annonce qu'elle met en œuvre un système de fluctuation du yuan dans les limites de 0,3 % par jour par rapport au dollar américain, contre 3 % maximum par rapport à un panier de devises étrangères, dont le yen et l'euro (voir Régime de change chinois)."),
                CustomImageCard("assets/chine/Hong_Kong_Skyline_Restitch_-_Dec_2007.jpg", "Compte tenu de la modernisation du pays, la société civile chinoise évolue à grande vitesse et adopte les nouveaux modes de consommation à l'instar des pays développés."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),

                TitreH1(' III ', " Rattrapage du retard économique"),
                DefaultText("On estime que la Chine a été la première puissance économique mondiale durant la majeure partie des vingt derniers siècles . Jusqu'au e siècle et la révolution industrielle, c'est également en Chine que l'on trouvait le niveau de vie le plus élevé de la planète . C'est sous la dynastie Qing que le développement économique de la Chine commença à ralentir, alors que les pays occidentaux passaient lentement d'une société à dominante agraire à une société industrielle. En 1820, la Chine comptait pour 33 % du PIB mondial, contre 9 % aujourd'hui ."),
                DefaultText("En 2010, la Chine est devenue la deuxième puissance mondiale : le PIB de la Chine s'est élevé à 5 878,6 milliards de dollars en 2010, contre 5 472 milliards au Japon . Ce développement effréné des activités économiques est davantage dû aux investissements et aux exportations qu'à la consommation intérieure . Début décembre 2014, le site américain MarketWatch annonce que la Chine devient officiellement la première puissance économique mondiale, sur la base d'un rapport du FMI d'octobre 2014 comparant le produit intérieur brut à parité de pouvoir d'achat. En effet, sur cette base, le PIB chinois, de 17 632 milliards de dollars, devrait dépasser celui de l'Amérique, de 17 416 milliards de dollars . Le FMI prévoit qu'elle atteindra 27 000 milliards de dollars de PIB en 2019, quand les États-Unis ne seront qu'à 22 000 milliards."),
                CustomImageCard("assets/chine/President_Xi_Jinping.jpg", "Officiels chinois menés par Xi Jinping face à une délégation économique néerlandaise conduite par Mark Rutte."),
                DefaultText("Le développement économique actuel de la Chine est l'un des plus rapides du monde, puisque l'on y enregistre une croissance dont la moyenne, en 25 ans, est de 9,8 % par an. Entre 1980 et 2007, le PIB a été multiplié par 12,7 . En 2013, la croissance en Chine a atteint 7,7 % . La république populaire de Chine est membre de l'Organisation mondiale du commerce (OMC) depuis le 11 décembre 2001 . La croissance de la Chine est essentiellement tirée par les exportations. Leur montant a plus que doublé en quatre ans, pour atteindre plus de 1 000 milliards de dollars américains en 2009, ce qui fait de la Chine le premier exportateur mondial. L'essentiel de ce commerce se fait avec l'Union européenne (20,4 %), les États-Unis (17,7 %), Hong Kong (13,4 %) et le Japon (8,1 %). La balance commerciale de la Chine est excédentaire avec un grand nombre de pays. Les points forts des exportations chinoises sont le textile, les tracteurs, les montres et les jouets (85 % du marché mondial), les appareils photographiques et les ordinateurs portables (55 % du marché), les téléviseurs et les machines à laver (30 %), 15 % pour l'acier ."),
                DefaultText("l'origine de la forte accélération de la croissance des exportations. Elles ont attiré la main-d'œuvre qualifiée dans les zones côtières où elles se sont implantées. Seulement 41 % des exportations chinoises proviennent d'entreprises intégralement chinoises. Aujourd'hui, 39 % des exportations en provenance de Chine sont réalisées par des entreprises dont le capital est à cent pour cent étranger et 20 % sont le fait de partenariat entre les sociétés étrangères et les sociétés chinoises . La Chine continentale entretient son attractivité pour les entreprises avec une main-d'œuvre bon marché et non syndiquée. Cependant le prix de la main-d'œuvre croît rapidement, en 2010, il a progressé de 24 % [réf. nécessaire] ."),
                CustomImageCard("assets/chine/220px-Shanghai_-_Nanjing_Road.jpeg", "Shanghai, grande ville mondiale, dynamique et moderne."),
                DefaultText("De plus, il faut ajouter que le pays possède la plus grande force de travail au monde avec 813,5 millions de travailleurs disponibles . La non-organisation des ouvriers chinois représente un bénéfice substantiel pour les employeurs, qui y trouvent une flexibilité d'emploi impossible à mettre en œuvre dans les démocraties libérales. Un autre aspect de l'économie chinoise à relever : les bas prix d'éléments non issus de la force de travail. Cela est dû en partie à l'existence du contrôle des prix et de la garantie des sources d'approvisionnement hérités de la précédente économie de type soviétique : les entreprises d'État continuant à être démantelées et leurs ouvriers renvoyés dans des secteurs de compétitivité accrus, l'effet déflationniste induit continue à mettre la pression sur les prix pratiqués au sein de l'économie [réf. nécessaire]."),
                DefaultText("Les conséquences de cette croissance économique sont nombreuses. Le revenu moyen annuel d'un ouvrier chinois est de mille trois cents dollars américains. Les salaires augmentent régulièrement sur le littoral pacifique. La Chine a accumulé la plus confortable réserve de devises de tous les temps: 2 200 milliards d'euros selon la Banque populaire de Chine."),
                DefaultText(
                    "En 2014, la Chine fonde la Banque asiatique d'investissement pour les infrastructures (AIIB) pour contrebalancer le poids des institutions financièresissues du monde occidental (et ce alors que plusieurs pays occidentaux acceptent toutefois d'en devenir membre). Dotée de dizaines de milliards de dollars, elle a pour but d'asseoir la nouvelle diplomatie économique chinoise afin de financer les besoins massifs en infrastructure en Asie (autoroutes, chemins de fer, télécommunications, etc.), à partir de réseaux financiers convergeant vers la Chine ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),
                

                TitreH1(' IV ', " Énergie"),
                DefaultText("La Chine est devenue la troisième consommatrice d'électricité après les États-Unis et l'Union européenne. La consommation par habitant, de l'ordre de 3 400 kWh par an (contre plus de 13 000 kWh/hab/an aux États-Unis), croît de façon très rapide. Les coupures d'électricité ou le rationnement sont fréquents dans le pays . Pourtant, 76 GW (180 % de ce que produit le Royaume-Uni) ont été ajoutés au parc électrique en 2011 et 2012. La production d'électricité a plus que triplé de 1990 à 2004. L'Agence internationale de l'énergie (AIE) prévoit que cette production doublera dans les dix prochaines années. Environ 75 % de cette électricité est produite par des centrales au charbon très nocives (émission de CO2 et de particules en suspension). Le charbon devrait continuer à dominer le secteur électrique chinois. Selon le MIT, la Chine construirait chaque semaine l'équivalent de deux nouvelles centrales au charbon, d'une capacité de 500 mégawatts électriques chacune. En 2019, les capacités des centrales à charbon chinoises atteignent près de 1 000 GW (contre un peu plus de 500 GW en 2005) ."),
                DefaultText("Pourtant, en 2009, la Chine devient le 3e producteur mondial d'électricité éolienne avec une capacité installée de 20 GW, derrière les États-Unis et l'Allemagne. Elle devient numéro un mondial en 2013 avec plus de 36 GW installés. Pour 2020, Pékin souhaite que les énergies vertes représentent 15 % de son mix énergétique ."),
                CustomImageCard("assets/chine/220px-Dreischluchtendamm_hauptwall_2006.jpg", "Le barrage des Trois-Gorges, dans la province du Hubei, est le plus grand barrage ainsi que le plus grand générateur d'électricité au monde "),
                DefaultText("La Chine s'oriente également vers un développement de l'électricité nucléaire. En 2010, six centrales nucléaires étaient construites dans les régions côtières et dix autres en construction. La capacité nucléaire installée était alors de 10 GW, elle est de 45,5 GW en 2019, soit 4,9 % de la production nationale d’électricité ."),
                DefaultText(
                    "Avec une consommation qui a doublé entre 2000 et 2006 (1 200 Mtep en 2006), la Chine consomme plus de charbon que les États-Unis, l'Europe et le Japon réunis, absorbant plus de 38 % du charbon consommé dans le monde. La part du charbon dans la consommation chinoise d'énergie primaire est de 70 % ; alors qu'elle avait tendance à régresser durant les années 1990 (passant de 76 % à 67,4 %), elle est repartie à la hausse depuis 2003. Le charbon joue donc un rôle-clé pour soutenir la croissance économique chinoise, dont les besoins énergétiques sont énormes. Deux facteurs permettent d'expliquer la domination du charbon : les réserves sont abondantes (les réserves prouvées sont évaluées à 114 milliards de tonnes, soit le 3e rang mondial derrière les États-Unis et la Russie ; les réserves totales sont estimées quant à elles à 5 570 milliards de tonnes par le China's General Geological Bureau) ce qui garantit l'indépendance énergétique, et c'est une énergie bon marché (notamment en raison du faible coût de la main-d'œuvre). Selon l'AIE, la croissance de la consommation de charbon devrait augmenter de 5,5 % par an jusqu'en 2015, puis de 1,7 % par an jusqu'en 2030."),
                DefaultText("La prévision pour 2030 est de 2 399 Mtep de charbon consommées annuellement, soit une augmentation de 119 % par rapport à 2005. En 2007, la Chine était le premier producteur de charbon, avec 2,35 milliards de tonnes, ce qui représente 44 % de la production mondiale . Les centrales thermiques au charbon causent de graves préjudices environnementaux, contribuant à faire de la Chine le plus important pollueur mondial . La part du nucléaire ne représente que 0,5 % de la production énergétique du pays. La Chine est le 5e producteur mondial de pétrole, pourtant, la production nationale ne suffit plus. L'implantation de derricks en mer dans la zone côtière du Vietnam fin 2013 a d'ailleurs provoqué de fortes tensions entre les deux pays. En 2005, en raison de sa forte croissance, la Chine a été contrainte d'importer 30 % de sa consommation de pétrole. Si cette croissance se maintient à ce rythme, en 2025, le pays importera 82 % de ses besoins en pétrole . Engagée dans de tels besoins pétroliers et gaziers, la Chine cherche à sécuriser ses approvisionnements en pétrole : la Russie, certains pays africains, les pays du Golfe et l'Iran sont ses fournisseurs. Par exemple, la Chine est en train d'investir près de quinze milliards d'euros pour construire un oléoduc et un gazoduc (de 2 380 et 2 800 kilomètres de long) afin d'acheminer le pétrole et le gaz du golfe du Bengale, jusqu'à Kunming dans le Yunnan, via le port de Kyaukpyu ."),
                DefaultText("L'exploitation de nouveaux champs pétrolifères dans le sud du pays ne suffira pas pour répondre à la demande et la maîtrise de l'exploitation en mer de Chine méridionale devient un enjeu stratégique. Par ailleurs, l'efficacité économique de l'énergie consommée est l'une des plus faibles au monde avec un ratio PIB/tonne équivalent pétrole des plus faibles ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),
                

                TitreH1(' V ', " Agriculture et ruralité"),
                DefaultText("Selon les estimations de l'Organisation de coopération et de développement économiques, le secteur agricole représente encore aujourd'hui 15 % du produit intérieur brut de la Chine et assure 40 % de l'ensemble des emplois. Une part qui s'élevait à 71 % à la fin des années 1970 . Ce secteur constitue donc, malgré le développement industriel récent, une part importante de l'économie chinoise. Plus de 700 millions de personnes vivent dans les zones rurales, avec de très fortes migrations vers les villes. À titre d'exemple, le Guangdong est passé de 35 millions d'habitants en 1987 à 105 millions en 2013, soit un triplement."),
                CustomImageCard("assets/chine/220px-Farmer_in_Tibet.jpg", "Fermiers tibétains."),
                DefaultText("L'agriculture, qui occupe la majeure partie de la population active (307 millions d'actifs ruraux), reste un secteur fondamental de l'économie chinoise. Les exploitations sont détenues par les collectivités villageoises qui les louent à des agriculteurs, souvent avec des baux de trente ans."),
                DefaultText("Cette semi-privatisation s'est accompagnée d'un boom de la productivité et de la production. Depuis 5 000 ans, le riz domine l'activité rurale de la Chine et constitue l'aliment de base de la majorité de ses habitants. L'agriculture chinoise est pénalisée par le peu de zones cultivables. En outre, elle dispose de seulement 10 % de la superficie cultivable mondiale et doit nourrir 22 % de la population mondiale. L'agriculture chinoise est également handicapée par son morcellement, avec 200 millions de foyers exploitant chacun, en moyenne, une superficie de 65 ares. De plus, du fait de l'urbanisation croissante, de la pollution et de la désertification, on estime que la surface cultivable diminue d'environ 2 500 km2 par an.[réf. nécessaire] Pourtant, entre 1990 et 2003, la production agricole a augmenté de 90 %. Bien que le parti communiste, sous l'impulsion de Mao Zedong se soit appuyé sur les paysans pour prendre le pouvoir, et qu'ils constituent donc la base de sa légitimité, ces derniers ont connu des fortunes diverses, reflétant les différentes options idéologiques suivies ces dernières décennies. Le gouvernement chinois reste néanmoins très attentif au sort des paysans, qui reste plus que jamais l'une de ses priorités. Pourtant, les aides publiques ne représentent que 6 % environ du revenu des agriculteurs, contre 20 % aux États-Unis, 34 % dans l'Union européenne et 58 % au Japon."),
                DefaultText("Les revenus des agriculteurs chinois ont cependant plus que triplé entre 1980 et 2000, ce qui a largement contribué à la diminution de la pauvreté dans le pays. 400 millions de Chinois vivant dans les zones rurales sont sortis de la pauvreté entre 1979 et 2002. Ceci n'empêche pas l'inégalité croissante entre ruraux et citadins. De ce fait, la Chine est confrontée à un exode rural important. Face aux conditions de plus en plus difficiles de leur vie, les paysans émigrent massivement vers les zones urbaines. On estime qu’environ 8 millions de paysans quittent la campagne chaque année pour rechercher un emploi, et que depuis 1979, entre 80 et 200 millions de paysans auraient émigré en ville.[réf. nécessaire] Par ailleurs, plusieurs parents partent pour la ville, abandonnant leurs enfants à la campagne avec les générations trop âgées pour travailler, du fait des mauvaises conditions par lesquelles ils seront employés ."),
                DefaultText("Les terres proches des grandes agglomérations sont convoitées pour faire face au développement urbain. Zhou Tianyong, un économiste influent, estime que, depuis le début des réformes jusqu'en 2003, environ 6 700 000 hectares ont été soustraits à l'agriculture."),
                CustomImageCard("assets/chine/220px-Tibet_labourDSCN1911.JPG", "Labour traditionnel au Tibet."),
                DefaultText("Les paysans n'ont été indemnisés qu'à hauteur de 10 % du prix du marché . Le 14 mars 2006, lors d'une conférence de presse, tenue à Pékin peu après la clôture de la session annuelle de la 10e Assemblée nationale populaire (ANP, parlement chinois), le Premier ministre chinois Wen Jiabao annonce que la Chine infligera une punition sévère à tout individu qui réquisitionnera illégalement des terres de paysans. Il faut souligner un paradoxe. Tandis que des terres agricoles sont menacées par l'étalement urbain, la construction des voies de communication et le développement d'une industrie rurale (de sous-traitance) mais aussi par des phénomènes de désertification, de lessivage des sols et d'érosion, la Chine a sur son territoire des fronts pionniers. Ces fronts pionniers sont différents de ceux que l'on trouve au Brésil. Ils ressemblent plutôt à des oasis : en effet ils sont installés dans des zones désertiques ou semi-désertiques de manière ponctuelle. On les trouve en particulier dans la région autonome du Xinjiang, où ils sont gérés par le Corps de production et de construction du Xinjiang."),
                DefaultText("Le sud du pays profite de cultures tropicales d'exportation ou d'autoconsommation. Sur les six premières années de la décennie 2010, le pays a conservé sa quatrième place au palmarès des grands producteurs mondiaux de sucre , malgré un déclin très accentué. Parmi les points forts de son agriculture, le pays était aussi deuxième au palmarès des producteurs mondiaux de céréales au milieu des années 2010, dominé par les États-Unis. La Chine était également première au palmarès producteurs mondiaux de thé sur la décennie 2010."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),
                

                TitreH1(' VI ', " Industries et matières premières"),
                DefaultText("La Chine possède également les plus importantes réserves de métaux rares au monde et dont l'utilisation principale est précisée ci-après entre parenthèses : 95 % des terres rares (nanotechnologie), 87 % de l'antimoine (semi-conducteur), 84 % du tungstène (métal le plus réfractaire, outils durs), 83 % du gallium (photovoltaïque), 79 % du germanium (fibre optique), 60 % de l'indium (écran plat, photovoltaïque) et 51 % de la fluorine (métallurgie, téflon, fréon). L'usage croissant de ces minerais dans les nouvelles technologies et l'industrie, face à une production concentrée et limitée, laisse craindre des risques de pénuries à plus ou moins long terme ."),
                DefaultText("Depuis les années 1990, la Chine est le premier fabricant mondial de jouets, la production étant concentrée principalement dans le Guangdong et les provinces du sud, avec une forte plateforme d'exportation à Hong Kong et dans le détroit de la rivière des Perles ."),
                Divider(
                  height: 20,
                  color: Colors.white,
                ),
                

                TitreH1(' VII ', " Monnaie chinoise"),
                DefaultText("Le yuan (chinois simplifié : 元 ; chinois traditionnel : 圓 ; pinyin : yuán) est la devise nationale de la république populaire de Chine, le nom officiel étant Renminbi (chinois simplifié : 人民币 ; chinois traditionnel : ⼈⺠幣 ; pinyin : rénmínbì), abrégé en RMB et signifiant « la devise du peuple »."),
                DefaultText("Bien que son nom officiel soit Renminbi, c'est le terme yuan qui est en général employé. Le yuan se subdivise en 10 jiao (ou 10 mao), eux-mêmes subdivisés en 10 fen. On trouve des billets de 1, 5, 10, 20, 50 et 100 yuans, des billets de 1, 2 et 5 jiaos, et des billets de 1, 2 et 5 fens (la production de ces trois derniers a été arrêtée en 2007). Les pièces, peu utilisées, sont de 1 yuan, 5 jiaos et 1, 2 et 5 fens ."),
                DefaultText("La Chine est souvent accusée de maintenir volontairement un taux de change bas pour faciliter ses exportations. Cette accusation est cependant démentie par le Trésor américain qui, dans son rapport semestriel du 19 décembre 2007, reconnait que Pékin ne manipule pas sa monnaie pour en tirer des bénéfices commerciaux , même s'il considère toujours que le yuan est sous-évalué par rapport au dollar ."),
                

              ],
            ),
          ),
        ]));
  }
}
